FROM node:22-slim as build-stage

WORKDIR /app


COPY frontend/package*.json ./
RUN npm install

COPY frontend/ .
ARG VITE_API_URL
ARG VITE_MEDIA_URL
ARG VITE_STRIPE_PUBLISHED_KEY
ENV VITE_STRIPE_PUBLISHED_KEY=$VITE_STRIPE_PUBLISHED_KEY
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_MEDIA_URL=$VITE_MEDIA_URL
RUN npm run build


FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]