services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-vue

    ports:
      - "8080:80"

  backend:
    build:
      context: .
      dockerfile: Dockerfile-django
    container_name: django
#    command: python stripe_integration_tz/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

    env_file:
      - .env