# Было: FROM node:18-slim as build-stage
# Стало:
FROM node:22-slim as build-stage

WORKDIR /app

# Дальше всё остается без изменений
COPY frontend/package*.json ./
RUN npm install

COPY frontend/ .
RUN npm run build

# Этап Nginx оставляем как есть
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]