server {
    listen 80;
    server_name localhost;

    # 1. Раздача фронтенда (Vue)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # ВАЖНО: Блок location /api/ МЫ УДАЛЯЕМ.
    # Фронтенд будет стучаться в бэкенд напрямую через интернет по ссылке.
}