server {
    listen 80;
    server_name localhost;

    # 1. Раздача фронтенда (уже есть)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 2. ДОБАВЛЯЕМ раздачу медиа
    location /media/ {
       	proxy_pass https://alluring-manifestation-production-84c6.up.railway.app/media/;
        proxy_set_header Host $host;
    }
}