server {
    listen 80;
    server_name localhost;

    # 1. Раздача фронтенда (уже есть)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /media/ {
        # Используем просто имя сервиса, как написано в панели Railway
        proxy_pass http://stripetest:8000/media/;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # Настройки, чтобы загрузка не висела вечно
        proxy_connect_timeout 5s;
        proxy_read_timeout 60s;
        proxy_buffering off;
    }
}