# Generated by Django 5.2.13 on 2026-04-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="category",
        ),
        migrations.AddField(
            model_name="item",
            name="categories",
            field=models.ManyToManyField(related_name="items", to="store.category"),
        ),
    ]
