# Generated by Django 5.2.13 on 2026-04-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_item_category_item_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="currency",
            field=models.CharField(default="rub"),
        ),
    ]
