# Generated by Django 5.2.13 on 2026-04-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_discount_item_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название налога (напр. НДС)"
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Процент налога"
                    ),
                ),
                (
                    "stripe_tax_rate_id",
                    models.CharField(
                        help_text="ID из панели Stripe (txr_...)", max_length=255
                    ),
                ),
            ],
        ),
    ]
